export * from 'modules/design/components/icons/base'
export * from 'modules/design/components/icons/logo'
export * from 'modules/design/components/icons/profile'
export * from 'modules/design/components/icons/arrow-left'
export * from 'modules/design/components/icons/loader'
